[tool.black]
line-length = 88
max-line-length = 88
target-version = ["py36", "py37", "py38", "py39"]
enforce_line_length = true
experimental_string_processing = true
exclude = '(*.txt)'

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_between_sections = 0
line_length = 88
